
# Site settings

url: "http://choicolateicecrimi.com"
# wedding-bot-url: "http://localhost:3000"
wedding-bot-url: "https://aisle-planner.herokuapp.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# baseurl: ""

google-tracking-id: "UA-71210506-5"

# Forces https everywhere in your website, except when you serve it locally

force-https: False

# Timezones
timezone: America/New_York
future: true

#############
# HTML Head #
#############

author: "Kevin Crimi & Melissa Choi"
lang: "en"
title: "Kevin & Melissa's Wedding"
favicon: "/img/favicon.ico"
description: "Information for Kevin and Melissa's wedding"
keywords: "Kevin Crimi, Melissa Choi, wedding, save the date, Nashville, wedding info, details, choicolateicecrimi"

################
# Images #
################

#background-img: "/img/scoop-bg.jpg"
#background-img: "/img/darkscoop.png"
background-img: "/img/cover.jpg"

############
# 404 page #
############

err-img: "/img/dim_sum.jpg"

#########################
# Sections in Home Page #
#########################

pages_list:
  - name: rsvp
    display: RSVP
    onIndex: True
    nav: False
  - name: 'lodging'
    display: 'Lodging'
    onIndex: False
    nav: True
  - name: 'schedule'
    display: 'Schedule'
    onIndex: False
    nav: True
  - name: 'recommendations'
    display: 'Recommendations'
    onIndex: False
    nav: True
  - name: 'registry'
    display: 'Registry'
    onIndex: False
    nav: True

##################
# External Links #
##################

links:
  sycamore: 'http://sycamorefarmsevents.com/'

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

# Pagination path
paginate_path: "past-shows/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor", "log.txt"]

# Fixes "Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem"
gems: [jekyll-paginate]
