
# Site settings

url: "http://choicolateicecrimi.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# baseurl: ""

google-tracking-id: "UA-71210506-5"

# Forces https everywhere in your website, except when you serve it locally

force-https: False

# Timezones
timezone: America/New_York
future: true

#############
# HTML Head #
#############

author: "Kevin Crimi & Melissa Choi"
lang: "en"
title: "Kevin & Melissa's Wedding"
favicon: "/img/favicon.ico"
description: "Information for Kevin and Melissa's wedding"
keywords: "Kevin Crimi, Melissa Choi, wedding, save the date, Nashville, wedding info, details, choicolateicecrimi"

################
# Images #
################

#background-img: "/img/scoop-bg.jpg"
background-img: "/img/darkscoop.png"

########
# Blog #
########

post-preview-words: 96

paginate: 25

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "panossakkos"

###############
# Life Events #
###############

events:
  - title: "Guitar"
    image: "/img/bubbles/guitar.png"
    description: "Trained in styles ranging from jazz to folk and specializing in fingerpicking, slide, and electric"
  - title: "Effects"
    image: "/img/bubbles/pedals.png"
    description: "Command of wide array of guitar FX to create atmospheric textures"
  - title: "Multi-Instrumentalist"
    image: "/img/bubbles/multi_instrumentalist.png"
    description: "Doubles on mandolin, pedal steel guitar, bass, drums, keys and vocals"
  - title: "Recording/Production"
    image: "/img/bubbles/pro_tools.png"
    description: "Comfortable engineering in a variety of software (Pro Tools, Reason, Kontakt)"
  - title: "Arranging"
    image: "/img/bubbles/sibelius.png"
    description: "Orchestration and arranging in Sibelius for high quality, professional scores"

# First image of the Career timeline
career-img: "/img/bubbles/BW_playing_guitar.png"

##################
# Contact layout #
##################

email:
  info: "Info@BrightwoodPatriarch.com"
  booking: "Booking@BrightwoodPatriarch.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "youtube"
    url: "https://youtube.com/"
  - title: "github"
    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-img: "/img/dim_sum.jpg"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  - name: 'about'
    display: 'Information'
    nav: True
  - name: 'rsvp'
    display: 'RSVP'
    nav: True

# Pagination path
paginate_path: "past-shows/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

# Fixes "Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem"
gems: [jekyll-paginate]
