
# Site settings

url: "http://choicolateicecrimi.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

# baseurl: ""

google-tracking-id: "UA-71210506-5"

# Forces https everywhere in your website, except when you serve it locally

force-https: False

# Timezones
timezone: America/New_York
future: true

#############
# HTML Head #
#############

author: "Kevin Crimi & Melissa Choi"
lang: "en"
title: "Kevin & Melissa's Wedding"
favicon: "/img/favicon.ico"
description: "Information for Kevin and Melissa's wedding"
keywords: "Kevin Crimi, Melissa Choi, wedding, save the date, Nashville, wedding info, details, choicolateicecrimi"

################
# Images #
################

#background-img: "/img/scoop-bg.jpg"
background-img: "/img/darkscoop.png"

############
# 404 page #
############

err-img: "/img/dim_sum.jpg"

#########################
# Sections in Home Page #
#########################

pages_list:
  - name: 'mailing'
    display: 'Mailing Info'
    nav: True
  - name: 'lodging'
    display: 'Lodging'
    nav: True

################
# Lodging Rows #
################

lodging:
  - name: 'Airbnb'
    img: 'airbnb.jpg'
    description: "If you've used Airbnb before, you know that it will be your best bet in terms of value. There are a variety of locations near the venue and in the city which can sleep small or large groups if you want to stay with a group of friends or family"
    code: "Sign up with our referral link for $40 credit"
    url: "http://www.airbnb.com/c/kcrimi"
  - name: 'Franklin Marriott Cool Springs'
    img: 'marriott.jpg'
    description: "Very modern hotel with free breakfast. $169 / night + tax"
    code: 'Group code: 123456'
    url: "https://www.marriott.com"
  - name: 'Courtyard Marriott & Residence Inn'
    img: 'courtyard.jpg'
    description: "Located right next to each other, the Courtyard Marriott offers $139 / night + tax for a king bed or 2 queens. The Residence Inn offers suites with a full kitchen, king bed, and queen pull out bed for $149 / night + tax."
    code: 'Group code: 1233456'
    url: "http://www.courtard.com"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

# Pagination path
paginate_path: "past-shows/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

# Fixes "Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem"
gems: [jekyll-paginate]
